"""F1 race strategy Gymnasium environment.

The agent controls a single driver's tyre strategy (when to pit, which
compound).  All field drivers replay their actual recorded lap times from
the gold layer, giving the agent a realistic competitive context.

The agent's lap times are generated by the LightGBM tyre-degradation model,
blended with physics-based synthetic degradation curves.

Observation space (20 float32 values):
    0  race_progress            fraction of race done (0–1)
    1  laps_remaining_norm      laps left / total laps
    2  own_tyre_life_norm       tyre age / 60 (clipped)
    3  own_compound_norm        compound_encoded / 5
    4  is_fresh_tyre            0 or 1
    5  own_synthetic_deg_norm   current degradation penalty / 5 (clipped ±1)
    6  position_norm            current position / n_drivers (lower = better)
    7  gap_ahead_s_norm         seconds to car ahead / 60 (clipped 0–1)
    8  gap_behind_s_norm        seconds to car behind / 60 (clipped 0–1)
    9  tyre_age_ahead_norm      car ahead tyre life / 60 (clipped 0–1)
   10  tyre_age_behind_norm     car behind tyre life / 60 (clipped 0–1)
   11  undercut_threat          1 if gap_behind<3s AND car behind has fresher tyres
   12  overcut_opportunity      1 if car ahead pitted in the last 2 laps
   13  free_stop_available      1 if SC/VSC active this lap (track_status >= 2)
   14  cars_lose_if_pit_norm    cars in pit window ahead / n_drivers
   15  pit_loss_norm            circuit pit loss time / 30
   16  sc_probability           SC onset probability from SC model (0–1)
   17  sc_laps_since_last_norm  laps since last SC / 50 (clipped)
   18  is_wet                   1 if >30% of field on INTER/WET this lap
   19  wet_fraction             fraction of field on wet compounds this lap

Action space (Discrete 4):
    0  Stay out
    1  Pit for SOFT   (compound_encoded = 0)
    2  Pit for MEDIUM (compound_encoded = 1)
    3  Pit for HARD   (compound_encoded = 2)

Reward:
    Per-lap:
        -sim_lap_time_s / 100                           (penalises slow laps)
        - over_cliff * 0.20 * cliff_urgency             (cliff penalty, fades in last 12 laps)
        - 20.0 if pit with ≤4 laps remaining            (hard veto on unrecoverable late pits)
        + max(0, position_change) * 1.0                 (bonus for gaining positions)
        - max(0, -position_change) * 0.5                (penalty for losing positions)
        + position_norm * 0.1                           (persistent track position signal)
        + 5.0 if pitting during SC/VSC                  (free stop bonus)
    Terminal: position_norm * 50  (P1 → +50, last place → 0)
"""

from __future__ import annotations

from typing import Any

import numpy as np
import pandas as pd

try:
    import gymnasium as gym
    from gymnasium import spaces
except ImportError as exc:  # pragma: no cover
    raise ImportError("Install gymnasium: uv add gymnasium>=0.29") from exc

from ml.models.safety_car.predict import predict_sc_probability
from services.simulator.lap_simulator import (
    PIT_LOSS_S,
    driver_baseline_delta,
    field_median_by_lap,
)

_ACTION_TO_COMPOUND: dict[int, int] = {1: 0, 2: 1, 3: 2}

# ---------------------------------------------------------------------------
# Module-level caches
#
# _RACE_ARRAY_CACHE: avoids rebuilding NumPy field arrays when the same
#   (year, round, driver) is reset again within the same process.
#
# _TIRE_TABLE_CACHE: avoids re-running batch tire model inference when the
#   same (driver baseline_delta, round_num) combination is seen again.
# ---------------------------------------------------------------------------
_RACE_ARRAY_CACHE: dict[tuple, dict] = {}
_TIRE_TABLE_CACHE: dict[tuple, np.ndarray] = {}

# Tire table quantisation — race_progress binned into 25 steps of 0.04 each.
_RP_BINS: int = 25
_RP_STEP: float = 1.0 / _RP_BINS
_MAX_TYRE_LIFE: int = 65  # table covers laps 0–64

_PIT_LOSS_BY_ROUND: dict[int, float] = {
    1: 23.0,   # Bahrain
    2: 23.0,   # Saudi Arabia
    3: 22.0,   # Australia
    4: 24.0,   # Japan
    5: 22.0,   # China
    6: 23.0,   # Miami
    7: 26.0,   # Emilia Romagna
    8: 25.0,   # Monaco
    9: 22.0,   # Canada
    10: 22.0,  # Spain
    11: 21.0,  # Austria
    12: 22.0,  # Britain
    13: 22.0,  # Hungary
    14: 22.0,  # Belgium
    15: 19.0,  # Netherlands (Zandvoort)
    16: 19.0,  # Monza
    17: 24.0,  # Azerbaijan
    18: 23.0,  # Singapore
    19: 22.0,  # USA (COTA)
    20: 23.0,  # Mexico
    21: 22.0,  # Brazil
    22: 23.0,  # Las Vegas
    23: 23.0,  # Qatar
    24: 22.0,  # Abu Dhabi
}

OBS_DIM: int = 20

# Compound_encoded values considered "wet" — INTER=3, WET=4.
_WET_COMPOUNDS: frozenset[int] = frozenset({3, 4})

# ---------------------------------------------------------------------------
# Synthetic tyre degradation — base values (fleet average, neutral conditions)
#
# compound_encoded:  0=SOFT  1=MEDIUM  2=HARD  3=INTER  4=WET  5=UNKNOWN
# ---------------------------------------------------------------------------
_BASE_DEGRADE_RATE: dict[int, float] = {0: 0.08, 1: 0.05, 2: 0.03, 3: 0.01, 4: 0.01, 5: 0.05}
_BASE_CLIFF_LAP: dict[int, int]      = {0: 22,   1: 32,   2: 42,   3: 50,   4: 50,   5: 35}

# ---------------------------------------------------------------------------
# Circuit-specific degradation multipliers (indexed by 2024 round number).
#
# Degradation multiplier: scales the base rate up/down.
# Cliff multiplier: scales the cliff lap — >1 means tyres last longer.
#
# Calibrated from Pirelli technical data and observed 2024 stint lengths.
# ---------------------------------------------------------------------------
_CIRCUIT_DEGRADE_MULT: dict[int, float] = {
    1:  1.20,  # Bahrain       — abrasive tarmac, high track temp
    2:  1.00,  # Saudi Arabia
    3:  0.90,  # Australia     — smooth Albert Park surface
    4:  0.85,  # Japan         — smooth Suzuka, cool conditions
    5:  1.10,  # China         — medium-high wear
    6:  1.15,  # Miami         — rough surface, tropical heat
    7:  0.95,  # Emilia Romagna
    8:  0.45,  # Monaco        — slow streets, tyres barely degrade
    9:  0.90,  # Canada        — heavy braking but cool
    10: 1.35,  # Spain         — famously brutal on tyres (Turn 9)
    11: 1.00,  # Austria
    12: 1.25,  # Britain       — Silverstone high-speed corners
    13: 1.10,  # Hungary       — high downforce, hot
    14: 0.90,  # Belgium       — Spa low tyre wear overall
    15: 1.10,  # Netherlands   — abrasive Zandvoort
    16: 0.55,  # Monza         — minimal cornering, very low wear
    17: 0.80,  # Azerbaijan    — smooth, mostly straight
    18: 0.65,  # Singapore     — slow, cool night race
    19: 1.15,  # USA (COTA)    — bumpy, high wear
    20: 1.00,  # Mexico        — high altitude, thin air
    21: 1.10,  # Brazil        — hot, high loads through Sector 3
    22: 0.85,  # Las Vegas     — smooth tarmac, cold night
    23: 1.25,  # Qatar         — extreme heat, very high wear
    24: 0.90,  # Abu Dhabi     — smooth Yas Marina
}

_CIRCUIT_CLIFF_MULT: dict[int, float] = {
    1:  0.85,  # Bahrain    — early cliff under heat
    8:  1.60,  # Monaco     — tyres last virtually the whole race
    10: 0.80,  # Spain      — earliest cliff on calendar
    12: 0.85,  # Britain
    16: 1.40,  # Monza      — long stints entirely viable
    17: 1.20,  # Azerbaijan
    18: 1.30,  # Singapore
    22: 1.15,  # Las Vegas
    23: 0.80,  # Qatar      — extreme heat accelerates cliff
}

# Reference track temperature (°C) for the base degradation values.
# Above this, degrade faster; below, degrade slower.
_REF_TRACK_TEMP_C: float = 35.0
_TEMP_DEG_COEFF: float = 0.018  # +1.8% degradation per °C above reference


def _compute_degrade_rate(
    round_num: int,
    track_temp_c: float | None = None,
    calibrated_rate: dict[int, float] | None = None,
) -> dict[int, float]:
    """Return per-compound degradation rates for a specific race weekend.

    Layered priority (highest wins):
      1. ``calibrated_rate`` — from practice long-run fitting
      2. Circuit multiplier × base rate
      3. Temperature adjustment applied on top

    Args:
        round_num: 2024 round number (1–24).
        track_temp_c: Mean race track temperature.  None disables temp adjustment.
        calibrated_rate: Per-compound rates from :func:`tyre_calibration.calibrate`.

    Returns:
        Dict mapping compound_encoded → degradation rate (s/lap).
    """
    if calibrated_rate is not None:
        rates = dict(calibrated_rate)
    else:
        mult = _CIRCUIT_DEGRADE_MULT.get(round_num, 1.0)
        rates = {k: v * mult for k, v in _BASE_DEGRADE_RATE.items()}

    if track_temp_c is not None:
        temp_mult = 1.0 + (track_temp_c - _REF_TRACK_TEMP_C) * _TEMP_DEG_COEFF
        temp_mult = max(0.5, min(2.0, temp_mult))  # clamp to sane range
        rates = {k: v * temp_mult for k, v in rates.items()}

    return rates


def _compute_cliff_lap(
    round_num: int,
    calibrated_cliff: dict[int, int] | None = None,
) -> dict[int, int]:
    """Return per-compound cliff laps for a specific circuit.

    Args:
        round_num: 2024 round number (1–24).
        calibrated_cliff: Per-compound cliff laps from :func:`tyre_calibration.calibrate`.

    Returns:
        Dict mapping compound_encoded → cliff lap number.
    """
    if calibrated_cliff is not None:
        return dict(calibrated_cliff)
    mult = _CIRCUIT_CLIFF_MULT.get(round_num, 1.0)
    return {k: max(5, int(v * mult)) for k, v in _BASE_CLIFF_LAP.items()}


def _synthetic_deg(
    compound: int,
    tyre_life: int,
    degrade_rate: dict[int, float],
    cliff_lap: dict[int, int],
) -> float:
    """Return lap time penalty (seconds) from tyre age, compound, and circuit rates."""
    rate = degrade_rate.get(compound, 0.05)
    cliff = cliff_lap.get(compound, 35)
    penalty = rate * tyre_life
    if tyre_life > cliff:
        penalty += (tyre_life - cliff) * rate * 3.0
    return penalty


class F1RaceEnv(gym.Env):
    """Single-driver F1 race strategy Gymnasium environment.

    Args:
        race_df: Gold DataFrame for one race (all drivers, session == "R").
        driver_number: The driver the agent controls.
        tire_model: Loaded MLflow pyfunc tyre-degradation model.
        sc_model: Optional loaded SC model; SC prob defaults to 0.0 if None.
        pit_loss_s: Seconds added on each pit-in lap (default 25 s).
        noise_std: Gaussian noise std added to simulated lap times (default 0.2 s).
    """

    metadata: dict[str, Any] = {"render_modes": []}

    def __init__(
        self,
        race_df: pd.DataFrame,
        driver_number: int | str,
        tire_model: Any,
        sc_model: Any | None = None,
        pit_loss_s: float = PIT_LOSS_S,
        noise_std: float = 0.2,
    ) -> None:
        super().__init__()

        self.action_space = spaces.Discrete(4)
        self.observation_space = spaces.Box(
            low=-np.inf, high=np.inf, shape=(OBS_DIM,), dtype=np.float32
        )

        self._tire_model = tire_model
        self._sc_model = sc_model
        self._pit_loss_s = pit_loss_s
        self._noise_std = noise_std

        self._init_race(race_df, driver_number)

    # ------------------------------------------------------------------
    # Initialisation helpers
    # ------------------------------------------------------------------

    def _init_race(
        self,
        race_df: pd.DataFrame,
        driver_number: int | str,
        calibrated_rate: dict[int, float] | None = None,
        calibrated_cliff: dict[int, int] | None = None,
    ) -> None:
        """Precompute all race-level data from the gold DataFrame.

        Args:
            race_df: Gold DataFrame for one race (all drivers).
            driver_number: Driver the agent controls.
            calibrated_rate: Per-compound degradation rates from practice fitting.
                             Overrides the circuit table when provided.
            calibrated_cliff: Per-compound cliff laps from practice fitting.
                              Overrides the circuit table when provided.
        """
        self._driver_number = driver_number
        agent_mask = race_df["driver_number"] == driver_number
        self._agent_df = (
            race_df[agent_mask].sort_values("lap_number").reset_index(drop=True)
        )

        self._total_laps: int = int(race_df["lap_number"].max())
        self._n_drivers: int = int(race_df["driver_number"].nunique())
        self._field_medians: pd.Series = field_median_by_lap(race_df)
        self._baseline_delta: float = driver_baseline_delta(self._agent_df)

        round_num = (
            int(race_df["round_number"].iloc[0])
            if "round_number" in race_df.columns
            else 0
        )
        self._pit_loss_s = _PIT_LOSS_BY_ROUND.get(round_num, self._pit_loss_s)

        # Circuit + temperature calibrated degradation parameters.
        track_temp = self._estimate_track_temp(race_df)
        self._degrade_rate: dict[int, float] = _compute_degrade_rate(
            round_num, track_temp, calibrated_rate
        )
        self._cliff_lap: dict[int, int] = _compute_cliff_lap(round_num, calibrated_cliff)

        # Batch-precompute tire model predictions over the full
        # (compound × tyre_life × race_progress × is_fresh) grid.
        # All subsequent step() calls use an O(1) numpy index lookup
        # instead of creating a DataFrame and invoking LightGBM pyfunc.
        tire_cache_key = round(self._baseline_delta, 3)
        if tire_cache_key not in _TIRE_TABLE_CACHE:
            _TIRE_TABLE_CACHE[tire_cache_key] = self._build_tire_table()
        self._tire_table: np.ndarray = _TIRE_TABLE_CACHE[tire_cache_key]

        field_df = race_df[~agent_mask]
        self._build_arrays(field_df, race_df)

    @staticmethod
    def _estimate_track_temp(race_df: pd.DataFrame) -> float | None:
        """Extract mean track temperature from gold data if the column exists."""
        for col in ("track_temp", "TrackTemp", "track_temperature"):
            if col in race_df.columns:
                vals = pd.to_numeric(race_df[col], errors="coerce").dropna()
                if len(vals):
                    return float(vals.mean())
        return None

    def _build_tire_table(self) -> np.ndarray:
        """Batch-predict tire degradation over the full input grid.

        Builds a single large DataFrame covering all combinations of
        (compound_encoded × tyre_life_laps × race_progress_bin × is_fresh_tyre)
        and calls the LightGBM pyfunc model once.  The result is reshaped into
        a 4-D float32 array indexed as [compound, tyre_life-1, rp_idx, is_fresh].

        Returns:
            NumPy array of shape (6, _MAX_TYRE_LIFE, _RP_BINS, 2).
        """
        n_rows = 6 * _MAX_TYRE_LIFE * _RP_BINS * 2
        compounds    = np.empty(n_rows, dtype=np.int32)
        tyre_lives   = np.empty(n_rows, dtype=np.int32)
        race_progs   = np.empty(n_rows, dtype=np.float32)
        is_fresh_arr = np.empty(n_rows, dtype=np.int32)

        i = 0
        for c in range(6):
            for tl in range(1, _MAX_TYRE_LIFE + 1):
                for rp_idx in range(_RP_BINS):
                    rp = (rp_idx + 0.5) * _RP_STEP  # bin midpoint
                    for fresh in range(2):
                        compounds[i]    = c
                        tyre_lives[i]   = tl
                        race_progs[i]   = rp
                        is_fresh_arr[i] = fresh
                        i += 1

        df = pd.DataFrame({
            "tyre_life_laps":              tyre_lives,
            "compound_encoded":            compounds,
            "race_progress":               race_progs,
            "track_status_encoded":        np.zeros(n_rows, dtype=np.int32),
            "is_fresh_tyre":               is_fresh_arr,
            "lap_delta_to_field_median_s": np.full(n_rows, self._baseline_delta, dtype=np.float32),
        })
        preds = self._tire_model.predict(df)
        return np.asarray(preds, dtype=np.float32).reshape(6, _MAX_TYRE_LIFE, _RP_BINS, 2)

    def _build_arrays(self, field_df: pd.DataFrame, race_df: pd.DataFrame) -> None:
        """Precompute all field state as NumPy arrays for fast per-step access.

        Arrays are indexed [driver_index, lap_number].  Lap 0 is unused;
        missing laps (retired drivers) are filled with sentinel values.
        """
        drivers = sorted(field_df["driver_number"].unique())
        self._field_drivers = drivers
        drv_to_idx = {drv: i for i, drv in enumerate(drivers)}
        n_field = len(drivers)
        total = self._total_laps

        # Cumulative race time — np.inf sentinel means driver not present that lap.
        self._field_cum_arr = np.full((n_field, total + 1), np.inf, dtype=np.float64)
        self._field_tyre_age_arr = np.full((n_field, total + 1), 15, dtype=np.int32)
        self._field_pitted_arr = np.zeros((n_field, total + 1), dtype=bool)

        median_fallback = np.array(
            [float(self._field_medians.get(lap) or 90.0) for lap in range(total + 1)]
        )

        for drv, grp in field_df.groupby("driver_number"):
            idx = drv_to_idx[drv]
            grp = grp.sort_values("lap_number")
            laps = grp["lap_number"].values.astype(int)
            lap_times = grp["lap_time_s"].values.astype(float)

            nan_mask = np.isnan(lap_times)
            lap_times[nan_mask] = median_fallback[laps[nan_mask]]
            self._field_cum_arr[idx, laps] = np.cumsum(lap_times)

            if "tyre_life_laps" in grp.columns:
                tl = pd.to_numeric(grp["tyre_life_laps"], errors="coerce").fillna(15)
                self._field_tyre_age_arr[idx, laps] = tl.values.astype(np.int32)

            if "pit_in_this_lap" in grp.columns:
                pit = grp["pit_in_this_lap"].fillna(False).astype(bool)
                self._field_pitted_arr[idx, laps] = pit.values

        # Wet fraction per lap — vectorized over all drivers including agent.
        self._wet_fraction_arr = np.zeros(total + 1, dtype=np.float32)
        wet_set = np.array(list(_WET_COMPOUNDS), dtype=int)
        for lap, grp in race_df.groupby("lap_number"):
            compounds = grp["compound_encoded"].dropna().values
            if len(compounds):
                self._wet_fraction_arr[int(lap)] = (
                    np.isin(compounds.astype(int), wet_set).sum() / len(compounds)
                )

        # Precompute track status per lap as array for O(1) lookup.
        self._track_status_arr = np.zeros(total + 1, dtype=np.int32)
        if "track_status_encoded" in self._agent_df.columns:
            for _, row in self._agent_df.iterrows():
                lap = int(row["lap_number"])
                val = row.get("track_status_encoded")
                if pd.notna(val) and lap <= total:
                    self._track_status_arr[lap] = int(val)

    # ------------------------------------------------------------------
    # Gymnasium API
    # ------------------------------------------------------------------

    def reset(
        self,
        *,
        seed: int | None = None,
        options: dict[str, Any] | None = None,
    ) -> tuple[np.ndarray, dict[str, Any]]:
        """Reset the environment for a new episode.

        Args:
            seed: RNG seed forwarded to the parent.
            options: Optional dict with ``race_df`` and ``driver_number`` keys
                to switch races between episodes.

        Returns:
            (observation, info) tuple per Gymnasium API.
        """
        super().reset(seed=seed)

        if options:
            race_df = options.get("race_df")
            drv = options.get("driver_number", self._driver_number)
            if race_df is not None:
                self._init_race(race_df, drv)

        first_row = self._agent_df.iloc[0] if not self._agent_df.empty else None
        start_compound = (
            int(first_row["compound_encoded"])
            if first_row is not None and pd.notna(first_row.get("compound_encoded"))
            else 1
        )

        self._lap: int = 1
        self._compound: int = start_compound
        self._tyre_life: int = 1
        self._is_fresh: bool = True
        self._cumulative_time_s: float = 0.0
        self._sc_laps_since_last: float = 30.0
        self._position: int = self._get_start_position()
        self._last_tire_delta: float = 0.0
        self._last_sc_prob: float = 0.0
        self._last_track_status: int = 0

        # Relative state (updated each step; initialised to neutral defaults)
        self._gap_ahead_s: float = 60.0
        self._gap_behind_s: float = 60.0
        self._tyre_age_ahead: int = 15
        self._tyre_age_behind: int = 15
        self._undercut_threat: float = 0.0
        self._overcut_opportunity: float = 0.0
        self._cars_lose_if_pit: int = 0
        self._wet_fraction_now: float = 0.0

        return self._build_obs(), {}

    def step(
        self, action: int
    ) -> tuple[np.ndarray, float, bool, bool, dict[str, Any]]:
        """Advance one lap.

        Args:
            action: 0=stay, 1=pit/soft, 2=pit/medium, 3=pit/hard.

        Returns:
            (obs, reward, terminated, truncated, info) per Gymnasium API.
        """
        is_pit = action > 0

        # Capture pre-pit state for cliff penalty calculation.
        pre_pit_compound = self._compound
        pre_pit_tyre_life = self._tyre_life

        if is_pit:
            self._compound = _ACTION_TO_COMPOUND[action]
            self._tyre_life = 1
            self._is_fresh = True

        race_prog = self._lap / self._total_laps
        track_status = self._read_track_status(self._lap)
        self._last_track_status = track_status

        if track_status >= 2:
            self._sc_laps_since_last = 0.0
        else:
            self._sc_laps_since_last = min(self._sc_laps_since_last + 1.0, 50.0)

        rp_idx = min(int(race_prog / _RP_STEP), _RP_BINS - 1)
        tl_idx = min(self._tyre_life - 1, _MAX_TYRE_LIFE - 1)
        tire_delta = float(self._tire_table[self._compound, tl_idx, rp_idx, int(self._is_fresh)])
        self._last_tire_delta = tire_delta

        if self._sc_model is not None and track_status == 0:
            self._last_sc_prob = predict_sc_probability(
                race_progress=race_prog,
                lap_number=self._lap,
                sc_laps_since_last=self._sc_laps_since_last,
                compound_encoded=self._compound,
                tyre_life_laps=float(self._tyre_life),
                position=float(self._position),
                model=self._sc_model,
            )
        else:
            self._last_sc_prob = 0.0

        # Blend: 30% LightGBM model + 70% physics-based synthetic degradation.
        syn_deg = _synthetic_deg(self._compound, self._tyre_life, self._degrade_rate, self._cliff_lap)
        blended_delta = 0.3 * tire_delta + 0.7 * syn_deg
        field_med = float(self._field_medians.get(self._lap) or 90.0)
        noise = float(self.np_random.normal(0.0, self._noise_std))
        sim_lap = field_med + self._baseline_delta + blended_delta + noise
        if is_pit:
            sim_lap += self._pit_loss_s

        self._cumulative_time_s += sim_lap
        self._tyre_life += 1
        self._is_fresh = False

        prev_position = self._position
        self._position = self._compute_position(self._lap)

        self._wet_fraction_now = float(self._wet_fraction_arr[self._lap])

        # Opponent gaps, undercut/overcut signals
        self._update_relative_state(self._lap)

        # Reward: penalise slow laps, reward position gains, bonus free stops.
        position_norm = (self._n_drivers - self._position) / max(self._n_drivers - 1, 1)
        position_change = prev_position - self._position  # positive = gained places
        free_stop_bonus = 5.0 if (is_pit and track_status >= 2) else 0.0

        # Cliff penalty: penalise laps driven past the compound's optimal stint window.
        # Scaled by laps remaining so urgency fades toward end of race — prevents the
        # policy learning to pit on the final lap just to escape the per-lap penalty.
        laps_remaining = max(0, self._total_laps - self._lap)
        cliff = self._cliff_lap.get(pre_pit_compound, 35)
        over_cliff = max(0, pre_pit_tyre_life - cliff)
        cliff_urgency = min(1.0, laps_remaining / 12.0)  # full weight if ≥12 laps left
        cliff_penalty = -over_cliff * 0.20 * cliff_urgency

        # Hard veto: pitting with ≤4 laps left almost never recovers the pit-loss time.
        late_pit_penalty = -20.0 if (is_pit and laps_remaining <= 4) else 0.0

        per_lap_reward = (
            -sim_lap / 100.0
            + cliff_penalty
            + late_pit_penalty
            + max(0.0, float(position_change)) * 1.0
            - max(0.0, float(-position_change)) * 0.5
            + position_norm * 0.1
            + free_stop_bonus
        )

        self._lap += 1
        terminated = self._lap > self._total_laps

        terminal_reward = position_norm * 50.0 if terminated else 0.0
        reward = per_lap_reward + terminal_reward

        obs = self._build_obs()
        info: dict[str, Any] = {
            "lap": self._lap - 1,
            "position": self._position,
            "sim_lap_time_s": round(sim_lap, 3),
            "compound": self._compound,
            "tyre_life": self._tyre_life - 1,
            "sc_probability": round(self._last_sc_prob, 3),
            "gap_ahead_s": round(self._gap_ahead_s, 1),
            "gap_behind_s": round(self._gap_behind_s, 1),
            "undercut_threat": bool(self._undercut_threat),
            "is_wet": self._wet_fraction_now > 0.3,
        }
        return obs, reward, terminated, False, info

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _get_start_position(self) -> int:
        lap1 = self._agent_df[self._agent_df["lap_number"] == 1]
        if not lap1.empty and pd.notna(lap1.iloc[0].get("position")):
            return int(lap1.iloc[0]["position"])
        return self._n_drivers // 2

    def _read_track_status(self, lap: int) -> int:
        """O(1) track status lookup using precomputed array."""
        if lap <= self._total_laps:
            return int(self._track_status_arr[lap])
        return 0

    def _compute_position(self, lap: int) -> int:
        """Vectorized: count field drivers with cumulative time < agent's."""
        col = self._field_cum_arr[:, lap]
        beaten_by = int(np.sum(col < self._cumulative_time_s))
        return beaten_by + 1  # 1-indexed

    def _update_relative_state(self, lap: int) -> None:
        """Vectorized gap, tyre age, undercut/overcut, and pit-cost signals."""
        agent_cum = self._cumulative_time_s
        col = self._field_cum_arr[:, lap]  # shape (n_field,)

        valid = col < np.inf
        if not valid.any():
            return

        valid_times = col[valid]
        valid_idxs = np.where(valid)[0]

        ahead_mask = valid_times < agent_cum
        behind_mask = ~ahead_mask

        if ahead_mask.any():
            ahead_times = valid_times[ahead_mask]
            ahead_global = valid_idxs[ahead_mask]
            # Closest ahead = highest cumulative time still below agent
            best = int(np.argmax(ahead_times))
            gi = ahead_global[best]
            self._gap_ahead_s = float(agent_cum - ahead_times[best])
            self._tyre_age_ahead = int(self._field_tyre_age_arr[gi, lap])
            prev = max(0, lap - 1)
            self._overcut_opportunity = float(
                self._field_pitted_arr[gi, lap] or self._field_pitted_arr[gi, prev]
            )
        else:
            self._gap_ahead_s = 60.0
            self._tyre_age_ahead = 15
            self._overcut_opportunity = 0.0

        if behind_mask.any():
            behind_times = valid_times[behind_mask]
            behind_global = valid_idxs[behind_mask]
            # Closest behind = lowest cumulative time still above agent
            best = int(np.argmin(behind_times))
            gi = behind_global[best]
            self._gap_behind_s = float(behind_times[best] - agent_cum)
            self._tyre_age_behind = int(self._field_tyre_age_arr[gi, lap])
            self._undercut_threat = float(
                self._gap_behind_s < 3.0
                and self._tyre_age_behind < self._tyre_life
            )
            pit_window = self._pit_loss_s + 5.0
            self._cars_lose_if_pit = int(
                np.sum(behind_times - agent_cum < pit_window)
            )
        else:
            self._gap_behind_s = 60.0
            self._tyre_age_behind = 15
            self._undercut_threat = 0.0
            self._cars_lose_if_pit = 0

    def _build_obs(self) -> np.ndarray:
        """Construct the 20-dimensional float32 observation vector."""
        syn_deg = _synthetic_deg(self._compound, self._tyre_life, self._degrade_rate, self._cliff_lap)
        wet_frac = self._wet_fraction_now
        return np.array(
            [
                # Own race state
                self._lap / self._total_laps,
                (self._total_laps - self._lap) / self._total_laps,
                min(self._tyre_life, 60) / 60.0,
                self._compound / 5.0,
                float(self._is_fresh),
                float(np.clip(syn_deg / 5.0, -1.0, 1.0)),
                # Track position
                self._position / self._n_drivers,
                # Relative state — gaps and neighbour tyre ages
                float(np.clip(self._gap_ahead_s / 60.0, 0.0, 1.0)),
                float(np.clip(self._gap_behind_s / 60.0, 0.0, 1.0)),
                float(np.clip(self._tyre_age_ahead / 60.0, 0.0, 1.0)),
                float(np.clip(self._tyre_age_behind / 60.0, 0.0, 1.0)),
                # Strategic signals
                self._undercut_threat,
                self._overcut_opportunity,
                float(self._last_track_status >= 2),  # free stop available
                self._cars_lose_if_pit / max(self._n_drivers - 1, 1),
                float(np.clip(self._pit_loss_s / 30.0, 0.0, 1.5)),
                # Safety car
                self._last_sc_prob,
                self._sc_laps_since_last / 50.0,
                # Weather
                float(wet_frac > 0.3),
                wet_frac,
            ],
            dtype=np.float32,
        )
